
export const GET_ACCOUNTS = 'accountList.GET_ACCOUNTS';
export const GET_ACCOUNTS_STARTED = 'accountList.GET_ACCOUNTS_STARTED';
export const GET_ACCOUNTS_SUCCESS = 'accountList.GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'accountList.GET_ACCOUNTS_FAILURE';

export const GET_ACCOUNTS_BYID = 'accountList.GET_ACCOUNTS_BYID';
export const GET_ACCOUNTS_BYID_STARTED = 'accountList.GET_ACCOUNTS_BYID_STARTED';
export const GET_ACCOUNTS_BYID_SUCCESS = 'accountList.GET_ACCOUNTS_BYID_SUCCESS';
export const GET_ACCOUNTS_BYID_FAILURE = 'accountList.GET_ACCOUNTS_BYID_FAILURE';

